{% set name = "pycvodes" %}
{% set version = "0.14.5" %}
{% set sha256 = "a365534e2d9280011bb2faa804da8bc3eb137e5042a3bce75ebd65019d674a02" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win and not py>=35]
  features:

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - liblapack
    - sundials <7
    - python
    - setuptools
    - pip
    - numpy
    - cython
  run:
    - sundials <7
    - python
    - setuptools  # pkg_resources used

test:
  imports:
    - pycvodes
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs {{ name }}
    - python -c "import pathlib as p; from pycvodes import get_include as g; assert open(p.Path(g()) / 'cvodes_cxx.hpp', 'rt').read().startswith('#pragma once')"

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python wrapper around cvodes (from the sundials library)
  doc_url: https://bjodah.github.io/{{ name }}/latest


extra:
  recipe-maintainers:
    - bjodah
    - moorepants
