{% set name = "pycvodes" %}
{% set version = "0.14.3" %}
{% set sha256 = "d2c5e2a41245b036dddb08605baaa5b8e36751fbeebef14b9975afa732d1c150" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and not py>=35]
  features:

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - liblapack
    - sundials
    - python
    - setuptools
    - pip
    - numpy
    - cython <3
  run:
    - sundials
    - python
    - setuptools  # pkg_resources used
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pycvodes
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs {{ name }}
    - python -c "import pathlib as p; from pycvodes import get_include as g; assert open(p.Path(g()) / 'cvodes_cxx.hpp', 'rt').read().startswith('#pragma once')"

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python wrapper around cvodes (from the sundials library)
  doc_url: https://bjodah.github.io/{{ name }}/latest


extra:
  recipe-maintainers:
    - bjodah
    - moorepants
