{% set name = "pycvodes" %}
{% set version = "0.11.5" %}
{% set sha256 = "375b791ee70e05ad3fae3e08c7935776b491b6c6f5ace99ed8f3694b366179a0" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true        # [win and not py>=35]
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas          # [not win]
    - sundials
    - python
    - setuptools
    - pip
    - numpy
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas                  # [not win]
    - sundials
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pycvodes
  requires:
    - pytest

about:
  home: https://github.com/bjodah/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Python wrapper around cvodes (from the sundials library)'
  doc_url: https://bjodah.github.io/{{ name }}/latest


extra:
  recipe-maintainers:
    - bjodah
