appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: b1aO/Lg6T/sZrGR7Iw9MIZUfqMpi2Br+bq6wMfM+IrP2m+6dMGkirNEg6wVpnFRPykTjZTH/nQlFAoC4BNkR0cGY7bI3GHwqpHEJaC2i3CA3CeAlROnoXx5awtWNy3vKIb6EngcXzkfmNSTYz6/ZSf2i1Ut2p8NteOywh5sDfZCVDs6VWB1wFprp563ujwKq2RslyRGLmHxDqkXc+QFGFGyLZJN9PqdGnu5JxJj4wYhx5kW75FAnVTlVd4V83gn8/izvOEV31NP1yLxkIXobXJ6tYRJqvEtQFF9dkXz/RbiUMYV+G8lTY/06Vx5mYvI7ok6EXKkW+qomyO8HsI7GDQMp1SJQ9qqp8iuCzAtBonK3JRy4cbGO60xtgNu0Zrbzm8nsL8100sC8YTUW88sPxE9fyPUgElWGQbqEUANmbPZxOmp9I9cFCPjOvlA58WbLFac3am9/hnxHetJyB7HvdiJ9dj9L/GmeJ78kRyGhkl9+e9MdiwtICJPjxQqyEgP/+98gr+ZG9QBLmBuURFsWzJrlRvsoVkP5AyT4hp30vi5kcH8Nqy3oICJKrKeCjvzVfwz/2Vu/NpldlBRK8LZ3IiMd9Rr3olum0dADWdfg+KOLluTU/TL2Ot/o17ySDHFmjUME/uVis5G2tkRSpk7ySGWHJsIDgdBmDnvs3Usi9x8=}
provider:
  win: azure
conda_forge_output_validation: true
